  lane :push do
  podspec = "Startup.podspec"
  last_version = version_get_podspec(path: podspec)
  version = version_bump_podspec(path: podspec)
  git_commit(path: [podspec], message: "Bump podspec to #{version}")
  changelog = changelog_from_git_commits
  changelog ||= "No changelog"
  github_release = set_github_release(
    repository_name: "pepibumur/Startup",
    api_token: ENV['GITHUB_TOKEN'],
    name: version,
    tag_name: version,
    description: changelog,
    commitish: "master"
  )
  sh("git fetch --tags")
  push_to_git_remote(remote_branch: 'master', force: false, tags: true)
  pod_push(allow_warnings: true, verbose: true)
end